runtime: nodejs18

env_variables:
  MONGODB_CONNECT_STRING: 'mongodb+srv://limpa:4JVVI36rEKyV3igo@cluster0.ifmwtzu.mongodb.net/'

automatic_scaling:
  min_idle_instances: 1
  max_instances: 1

inbound_services:
- warmup